## idiomas


idioma <- list(Intro = list(pt = "Instruções Gerais",
                            en = "General instructions"),
               Draw = list(pt = "Defina a distribuição", 
                           en = "Define the distribution"),
               instructions = list(pt = "general_instructions_pt.Rmd",
                                  en = "general_instructions_en.Rmd"),
               name = list(pt = "Nome completo:",
                           en = "Full name:"), 
               name.output = list(pt = "Nome:", 
                                  en = "Name:"),
               map1.help.text = list(pt = "map_instructions_pt.Rmd",
                                    en = "map_instructions_en.Rmd"),
               map2.help.text = list(pt = "map2_instructions_pt.Rmd",
                                     en = "map2_instructions_en.Rmd"),
               map.ok = list(pt = "Clique aqui ao terminar de desenhar os poligonos:",
                              en = "Click here when you finished drawing poligons:"),
               drew = list(pt = "Você desenhou",
                           en = "You drew"),
               singular = list(pt = "polígono",
                               en = "polygon"),
               plural = list(pt = "polígonos",
                             en = "polygons"),
               end.step1 = list(pt = "Você finalizou o passo 1",
                                en = "You have finished the step 1"),
               end.step2 = list(pt = "Tarefa finalizada!",
                                en = "Task Finished!"),
               opacity = list(pt = "Escolha a opacidade da camada:",
                              en = "Change layer opacity:"),
               opacity.level = list(pt = list("baixa", "alta"),
                                    en = list("low","high")),
               legend.map = list(pt = "Cobertura de Campo (%)",
                                 en = "Grassland cover (%)"),
               download = list(pt = c("Muito obrigado por compartilhar seu conhecimento conosco!",
                                      "Por favor, beixe o arquivo com os resultados e envie para",
                                      " com o assunto "),
                               en = c("Thank you for sharing your knowledge with us!",
                                      "Please, download the file with the results and mail it to ",
                                      " with the subject ")))


